### ISSUE TITLE
功能很全面，很厉害哦！

### ISSUE THREAD

**Issue by kaingeyy** [kehengzhong/ejet#2]
怎么定位是嵌入式的web呢？ 功能这么全面服务器上也可以用吧？

**Comment by kehengzhong** [comment]
好问题，eJet为什么定位为嵌入式Web服务器？

1. eJet作为Web服务器完全媲美Nginx，架构、性能、灵活性、扩展性等方面跟Nginx相比有相当独到之处，完全可以用于商业用途的Web服务器、正向代理服务器、反向代理服务器、负载均衡服务器、Web Cache系统等应用场景；

2. 嵌入式的定义是指eJet可以无缝地集成到其他系统，并作为其系统的一部分。eJet可以编译成静态库（.a）或动态库（.so），体积较小，可根据并发能力配置更低的线程数和其他内核资源消耗，通过回调机制，很容易地被业务应用系统嵌入和集成，使得业务应用系统最终具备HTTP/HTTPS服务能力。

3. 此外，对于嵌入式设备，部署一个重量级的Nginx或Apache作为Web服务器等，费效比太高，在提供足够Web服务能力前提下，使用eJet的性价比更高。

**Comment by kaingeyy** [comment]
彩～，抽空整个编译说明吧，跑起来看看效果
